import { IoWater, IoSnow, IoHome, IoFlash } from "react-icons/io5";
import { IssueData } from "./types";

export const issuesData: Record<string, IssueData> = {
  current: {
    title: "Leaky kitchen faucet",
    icon: IoWater,
    iconColor: "text-blue-500",
    status: "active",
    date: "Just now",
    preview: "Water dripping from handle...",
    diagnosis: "Worn O-ring or cartridge seal causing leak at handle base",
    difficulty: "Easy",
    estimatedTime: "30-45 min",
    diyCost: 33.48,
    proCost: 185,
    confidence: 92,
    parts: [
      {
        name: "Moen 1225 Cartridge",
        price: 29.98,
        store: "Home Depot",
        address: "1234 Main St, San Jose",
        distance: "0.8 mi",
        inStock: true,
        link: "https://www.homedepot.com/s/moen%201225%20cartridge",
      },
      {
        name: "O-Ring Kit",
        price: 5.98,
        store: "Home Depot",
        address: "1234 Main St, San Jose",
        distance: "0.8 mi",
        inStock: true,
        link: "https://www.homedepot.com/s/faucet%20o-ring%20kit",
      },
    ],
    safety: {
      ppe: ["Safety Glasses", "Work Gloves"],
      doNotProceed: ["Turn off water supply at shutoff valves under sink"],
    },
    research: [
      { type: "reddit", title: "r/Plumbing: Moen faucet drip fix - worked perfectly", meta: "234 upvotes · 47 comments", url: "reddit.com/r/Plumbing/..." },
      { type: "reddit", title: "r/HomeImprovement: Same issue, O-ring was the culprit", meta: "89 upvotes · 23 comments", url: "reddit.com/r/HomeImprovement/..." },
      { type: "youtube", title: "How to Replace Moen Cartridge in 10 Minutes", meta: "1.2M views · 4.8★", url: "youtube.com/watch?v=..." },
    ],
    guides: [
      { source: "YouTube", title: "Moen Faucet Cartridge Replacement", duration: "12:34", rating: 4.8, icon: "youtube" },
      {
        source: "iFixit",
        title: "Moen Single Handle Faucet Repair",
        url: "https://www.ifixit.com/Guide/Moen+Single+Handle+Faucet+Cartridge+Replacement",
        steps: 8,
        rating: 4.7,
        icon: "ifixit",
        toolsNeeded: ["Flathead screwdriver", "Phillips screwdriver", "Needle-nose pliers", "Adjustable wrench", "Cartridge puller (optional)"],
        stepContent: [
          { stepNumber: 1, title: "Turn off water supply", description: "Locate the shutoff valves under the sink and turn them clockwise to close." },
          { stepNumber: 2, title: "Remove handle cap", description: "Pry off the decorative cap on the handle using a flathead screwdriver." },
          { stepNumber: 3, title: "Unscrew handle", description: "Remove the Phillips screw and pull the handle straight up and off." },
          { stepNumber: 4, title: "Remove retaining clip", description: "Use needle-nose pliers to remove the U-shaped retaining clip." },
          { stepNumber: 5, title: "Pull out old cartridge", description: "Use the Moen cartridge puller or pliers to pull the cartridge straight out." },
          { stepNumber: 6, title: "Install new cartridge", description: "Push the new cartridge in, aligning the tabs with the slots in the valve body." },
          { stepNumber: 7, title: "Reassemble handle", description: "Replace the retaining clip, handle, screw, and decorative cap." },
          { stepNumber: 8, title: "Test for leaks", description: "Turn water back on slowly and check for leaks around the handle and spout." },
        ],
      },
      {
        source: "Family Handyman",
        title: "Fix a Leaky Faucet in 15 Minutes",
        url: "https://www.familyhandyman.com/project/fix-a-leaky-faucet",
        steps: 6,
        icon: "article",
        toolsNeeded: ["Adjustable wrench", "Screwdriver set", "Pliers"],
        stepContent: [
          { stepNumber: 1, title: "Shut off the water", description: "Turn off both hot and cold shutoff valves under the sink." },
          { stepNumber: 2, title: "Remove the handle", description: "Pop off the cap, remove the screw, and lift off the handle." },
          { stepNumber: 3, title: "Inspect the cartridge", description: "Look for cracks, wear, or mineral buildup on the cartridge." },
          { stepNumber: 4, title: "Replace O-rings", description: "If only the O-rings are worn, replace them with new ones from your kit." },
          { stepNumber: 5, title: "Install replacement parts", description: "Insert the new cartridge or O-rings and reassemble." },
          { stepNumber: 6, title: "Test your repair", description: "Turn on the water and check that the leak is fixed." },
        ],
      },
      { source: "This Old House", title: "How to Replace a Faucet Cartridge", duration: "8:45", icon: "youtube" },
    ],
    pros: [
      { name: "Mike's Plumbing", rating: 4.8, reviews: 127, distance: "2.3 mi", address: "892 Willow Rd, San Jose", price: 185, available: "Today 2-5pm", source: "angi", email: "mike@mikesplumbing.com", phone: "(408) 555-1234", calendarSlots: ["Today 2:00 PM", "Today 4:30 PM", "Tomorrow 9:00 AM"] },
      { name: "Quick Fix Pros", rating: 4.6, reviews: 89, distance: "3.1 mi", address: "445 Cedar Blvd, Santa Clara", price: 210, available: "Tomorrow 9am", source: "yelp", email: "info@quickfixpros.com", phone: "(408) 555-5678", calendarSlots: ["Tomorrow 9:00 AM", "Tomorrow 2:00 PM"] },
      { name: "Bay Plumbing Co", rating: 4.5, reviews: 156, distance: "4.2 mi", address: "789 Oak St, Sunnyvale", price: 175, available: "Today 5pm", source: "thumbtack", email: "service@bayplumbing.com", phone: "(408) 555-9012", calendarSlots: ["Today 5:00 PM", "Friday 10:00 AM"] },
    ],
    chatMessages: [
      { role: "assistant", content: "Hey! I'm here to help diagnose your home issue. You can describe the problem, upload a photo, or even record a voice note. What's going on?" },
      { role: "user", content: "My kitchen faucet has been dripping. Here's a photo.", hasImage: true },
      { role: "assistant", content: "I can see the issue! Based on the photo, it looks like **water is dripping from the base of the handle** when the faucet is on.\n\nThis is typically caused by a **worn O-ring or cartridge seal** - a very common fix!\n\n**Good news:** This is an easy DIY repair that takes about 30-45 minutes. I've found parts in stock nearby and video guides to walk you through it." },
    ],
    permit: { required: false },
    seasonalTip: { tip: "Check all faucet washers before winter - frozen pipes can cause leaks", season: "Fall", urgency: "medium" },
    followUp: { enabled: true, nextCheck: "3 days", message: "How did the faucet repair go? Need any help?" },
    avgAreaCost: { low: 150, high: 250, source: "HomeAdvisor" },
  },
  "2": {
    title: "AC not cooling properly",
    icon: IoSnow,
    iconColor: "text-blue-500",
    status: "resolved",
    date: "2 days ago",
    preview: "Diagnosed: Low refrigerant",
    diagnosis: "Low refrigerant levels - likely slow leak in system requiring professional service",
    difficulty: "Professional Required",
    estimatedTime: "2-3 hours",
    diyCost: 0,
    proCost: 350,
    confidence: 88,
    parts: [],
    safety: {
      ppe: ["N/A - Professional service required"],
      doNotProceed: ["Do not attempt to recharge refrigerant yourself - requires EPA 608 certification", "Refrigerant handling is illegal without certification"],
    },
    research: [
      { type: "reddit", title: "r/HVAC: AC not cooling - how to know if it's refrigerant", meta: "456 upvotes · 89 comments", url: "reddit.com/r/HVAC/..." },
      { type: "youtube", title: "Signs Your AC Needs Refrigerant (Don't DIY This)", meta: "890K views · 4.6★", url: "youtube.com/watch?v=..." },
      { type: "reddit", title: "r/HomeImprovement: When to call an HVAC pro vs DIY", meta: "123 upvotes · 34 comments", url: "reddit.com/r/HomeImprovement/..." },
    ],
    guides: [],
    pros: [
      { name: "Cool Air HVAC", rating: 4.9, reviews: 203, distance: "1.8 mi", address: "123 Tech Blvd, San Jose", price: 350, available: "Today 4pm", source: "angi", email: "service@coolairhvac.com", phone: "(408) 555-2345", calendarSlots: ["Today 4:00 PM", "Tomorrow 8:00 AM", "Tomorrow 1:00 PM"] },
      { name: "Bay Area Cooling", rating: 4.7, reviews: 156, distance: "4.2 mi", address: "789 Industrial Way, Santa Clara", price: 295, available: "Tomorrow 10am", source: "yelp", email: "info@bayareacooling.com", phone: "(408) 555-3456", calendarSlots: ["Tomorrow 10:00 AM", "Tomorrow 3:00 PM"] },
      { name: "HVAC Masters", rating: 4.8, reviews: 312, distance: "5.1 mi", address: "456 Service Dr, Mountain View", price: 325, available: "Today 6pm", source: "homeadvisor", email: "contact@hvacmasters.com", phone: "(408) 555-7890", calendarSlots: ["Today 6:00 PM", "Friday 9:00 AM"] },
    ],
    chatMessages: [
      { role: "user", content: "My AC is running but not cooling the house. It's 85°F inside and thermostat is set to 72°F." },
      { role: "assistant", content: "Based on your description - AC running but not cooling - this is typically caused by **low refrigerant levels**, which indicates a leak in the system.\n\n⚠️ **Important:** Refrigerant handling requires EPA 608 certification. This is **not a DIY repair** - it's actually illegal to handle refrigerants without proper certification.\n\nI found 3 highly-rated HVAC pros near you and sent quote requests to all of them. Cool Air HVAC has availability **today at 4pm** and excellent reviews." },
    ],
    permit: { required: false },
    seasonalTip: { tip: "Schedule AC maintenance in early spring before peak summer demand", season: "Spring", urgency: "high" },
    followUp: { enabled: true, nextCheck: "1 day", message: "Did Cool Air HVAC fix the AC issue? Rate your experience." },
    avgAreaCost: { low: 250, high: 450, source: "Thumbtack" },
  },
  "3": {
    title: "Garage door squeaking",
    icon: IoHome,
    iconColor: "text-amber-500",
    status: "pending",
    date: "1 week ago",
    preview: "Needs lubrication",
    diagnosis: "Dry rollers and hinges causing squeaking during operation",
    difficulty: "Easy",
    estimatedTime: "15-20 min",
    diyCost: 12.98,
    proCost: 95,
    confidence: 95,
    parts: [
      {
        name: "White Lithium Grease",
        price: 6.98,
        store: "Home Depot",
        address: "1234 Main St, San Jose",
        distance: "0.8 mi",
        inStock: true,
        link: "https://www.homedepot.com/s/white%20lithium%20grease",
      },
      {
        name: "Silicone Spray Lubricant",
        price: 7.98,
        store: "Home Depot",
        address: "1234 Main St, San Jose",
        distance: "0.8 mi",
        inStock: true,
        link: "https://www.homedepot.com/s/silicone%20spray%20lubricant",
      },
    ],
    safety: {
      ppe: ["Safety Glasses", "Work Gloves"],
      doNotProceed: ["Disconnect automatic opener before manual operation", "Never lubricate the tracks - door can slip off"],
    },
    research: [
      { type: "youtube", title: "Garage Door Maintenance 101 - Stop the Squeak!", meta: "2.1M views · 4.9★", url: "youtube.com/watch?v=..." },
      { type: "reddit", title: "r/HomeImprovement: Best garage door lubricant?", meta: "312 upvotes · 67 comments", url: "reddit.com/r/HomeImprovement/..." },
      { type: "reddit", title: "r/garagedoors: Monthly maintenance checklist", meta: "189 upvotes · 42 comments", url: "reddit.com/r/garagedoors/..." },
    ],
    guides: [
      { source: "YouTube", title: "Complete Garage Door Lubrication Guide", duration: "8:12", rating: 4.9, icon: "youtube" },
      {
        source: "Family Handyman",
        title: "Garage Door Maintenance in 20 Minutes",
        url: "https://www.familyhandyman.com/project/garage-door-tune-up",
        steps: 5,
        icon: "article",
        toolsNeeded: ["Clean cloth", "White lithium grease", "Silicone spray", "Step ladder"],
        stepContent: [
          { stepNumber: 1, title: "Disconnect the opener", description: "Pull the emergency release cord to disconnect the automatic opener." },
          { stepNumber: 2, title: "Clean the tracks", description: "Wipe down the tracks with a damp cloth to remove dirt and debris." },
          { stepNumber: 3, title: "Lubricate the hinges", description: "Apply white lithium grease to all hinges where metal meets metal." },
          { stepNumber: 4, title: "Lubricate the rollers", description: "Spray silicone lubricant on roller bearings (not nylon rollers)." },
          { stepNumber: 5, title: "Reconnect and test", description: "Reconnect the opener and test the door for smooth, quiet operation." },
        ],
      },
      { source: "This Old House", title: "How to Quiet a Noisy Garage Door", duration: "6:30", icon: "youtube" },
    ],
    pros: [
      { name: "Precision Garage Doors", rating: 4.8, reviews: 94, distance: "3.5 mi", address: "456 Commerce Dr, Sunnyvale", price: 95, available: "Friday 10am", source: "yelp", email: "service@precisiondoors.com", phone: "(408) 555-4567", calendarSlots: ["Friday 10:00 AM", "Friday 2:00 PM"] },
    ],
    chatMessages: [
      { role: "user", content: "Here's a voice note about my garage door issue", hasVoice: true },
      { role: "assistant", content: "I transcribed your voice note:\n\n*\"My garage door makes a loud squeaking noise when opening and closing\"*\n\nSqueaky garage doors are usually caused by **dry rollers, hinges, or springs** that need lubrication.\n\n**This is an easy 15-20 minute DIY fix!** You'll need white lithium grease for the hinges and springs, and silicone spray for the rollers.\n\n⚠️ **Safety note:** Disconnect the automatic opener before working on the door, and **never lubricate the tracks** - this can cause the door to slip off." },
    ],
    permit: { required: false },
    seasonalTip: { tip: "Lubricate garage door every 6 months - squeaks worsen in cold weather", season: "Fall/Spring", urgency: "low" },
    followUp: { enabled: true, nextCheck: "6 months", message: "Time for garage door maintenance! Re-lubricate hinges and rollers." },
    avgAreaCost: { low: 75, high: 150, source: "Thumbtack" },
  },
  "4": {
    title: "Flickering lights",
    icon: IoFlash,
    iconColor: "text-yellow-500",
    status: "resolved",
    date: "2 weeks ago",
    preview: "Loose connection found",
    diagnosis: "Loose wire connection at switch or fixture - potential fire hazard",
    difficulty: "Moderate - Electrical",
    estimatedTime: "30-60 min",
    diyCost: 0,
    proCost: 125,
    confidence: 78,
    parts: [],
    safety: {
      ppe: ["Voltage Tester", "Insulated Gloves", "Safety Glasses"],
      doNotProceed: ["Turn off circuit breaker AND verify power is off with voltage tester", "Never assume power is off - always test", "If you see burn marks or smell burning, call electrician immediately"],
    },
    research: [
      { type: "reddit", title: "r/electricians: Flickering lights - when to worry", meta: "567 upvotes · 123 comments", url: "reddit.com/r/electricians/..." },
      { type: "youtube", title: "Diagnosing Flickering Lights Safely", meta: "450K views · 4.5★", url: "youtube.com/watch?v=..." },
      { type: "reddit", title: "r/HomeImprovement: Fixed my flickering light - loose neutral", meta: "234 upvotes · 56 comments", url: "reddit.com/r/HomeImprovement/..." },
    ],
    guides: [
      { source: "YouTube", title: "How to Safely Check Electrical Connections", duration: "15:20", rating: 4.7, icon: "youtube" },
      {
        source: "Family Handyman",
        title: "Troubleshooting Flickering Lights",
        url: "https://www.familyhandyman.com/electrical/troubleshooting-flickering-lights",
        steps: 7,
        icon: "article",
        toolsNeeded: ["Non-contact voltage tester", "Flathead screwdriver", "Phillips screwdriver", "Flashlight"],
        stepContent: [
          { stepNumber: 1, title: "Note the flicker pattern", description: "Observe when flickering occurs - with appliances, randomly, or constantly." },
          { stepNumber: 2, title: "Check the bulb", description: "Ensure the bulb is screwed in tightly. Try a different bulb to rule it out." },
          { stepNumber: 3, title: "Turn off the breaker", description: "Locate the circuit breaker and turn it off. Verify with a voltage tester." },
          { stepNumber: 4, title: "Inspect the switch", description: "Remove the switch plate and check for loose wire connections." },
          { stepNumber: 5, title: "Check the fixture", description: "Examine the light fixture for loose wires at the connection point." },
          { stepNumber: 6, title: "Tighten connections", description: "Use a screwdriver to tighten any loose wire nuts or terminal screws." },
          { stepNumber: 7, title: "Test the repair", description: "Restore power and test. If flickering persists, call an electrician." },
        ],
      },
    ],
    pros: [
      { name: "Spark Electric", rating: 4.9, reviews: 178, distance: "2.1 mi", address: "321 Electric Ave, San Jose", price: 125, available: "Today 3pm", source: "angi", email: "service@sparkelectric.com", phone: "(408) 555-5678", calendarSlots: ["Today 3:00 PM", "Today 5:30 PM", "Tomorrow 10:00 AM"] },
      { name: "Safe Home Electrical", rating: 4.7, reviews: 112, distance: "5.0 mi", address: "654 Power St, Santa Clara", price: 150, available: "Tomorrow 8am", source: "yelp", email: "info@safehomeelectric.com", phone: "(408) 555-6789", calendarSlots: ["Tomorrow 8:00 AM", "Tomorrow 1:00 PM"] },
      { name: "Premier Electric", rating: 4.6, reviews: 89, distance: "3.8 mi", address: "987 Volt Way, Campbell", price: 135, available: "Today 6pm", source: "thumbtack", email: "jobs@premierelectric.com", phone: "(408) 555-3210", calendarSlots: ["Today 6:00 PM", "Friday 11:00 AM"] },
    ],
    chatMessages: [
      { role: "user", content: "The lights in my living room keep flickering, especially when the AC kicks on" },
      { role: "assistant", content: "Flickering lights when high-draw appliances start can indicate:\n\n1. **Normal voltage drop** - minor flicker is common\n2. **Loose connection** - at switch, fixture, or panel (fire hazard)\n3. **Overloaded circuit** - too many devices on one circuit\n\n⚠️ **Warning:** Loose electrical connections are a leading cause of house fires. If flickering is persistent or you see/smell burning, call an electrician immediately.\n\nI've sent quote requests to 3 electricians and checked your calendar for availability. Spark Electric has same-day availability that matches your open slots." },
    ],
    permit: { required: true, type: "Electrical Permit", cost: 85, processingTime: "1-3 business days", municipality: "City of San Jose" },
    seasonalTip: { tip: "Holiday lights can overload circuits - check breaker capacity before decorating", season: "Winter", urgency: "medium" },
    followUp: { enabled: false, nextCheck: "", message: "" },
    avgAreaCost: { low: 100, high: 200, source: "HomeAdvisor" },
  },
};
