import {
  IoWater,
  IoSnow,
  IoHome,
  IoFlash,
  IoConstruct,
} from "react-icons/io5";
import type { Issue, ChartDataItem, SavingsDataItem } from "./types";

export const issuesHistoryData: Issue[] = [
  {
    id: "1",
    title: "Leaky kitchen faucet",
    icon: IoWater,
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/20",
    status: "investigating",
    priority: "medium",
    category: "Plumbing",
    group: "My Apartment",
    createdAt: "2 days ago",
    updatedAt: "Just now",
    diagnosis: "Worn O-ring or cartridge seal",
    confidence: 92,
    difficulty: "Easy",
    diyCost: 33.48,
    proCost: 185,
    resolvedBy: null,
    assignee: { name: "Alex Chen" },
  },
  {
    id: "2",
    title: "AC not cooling properly",
    icon: IoSnow,
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/20",
    status: "in_progress",
    priority: "high",
    category: "HVAC",
    group: "My Apartment",
    createdAt: "1 week ago",
    updatedAt: "2 days ago",
    diagnosis: "Low refrigerant levels - requires professional",
    confidence: 88,
    difficulty: "Professional Required",
    diyCost: 0,
    proCost: 350,
    resolvedBy: null,
    assignee: { name: "Jamie Lee" },
  },
  {
    id: "3",
    title: "Garage door squeaking",
    icon: IoHome,
    iconColor: "text-amber-400",
    iconBg: "bg-amber-500/20",
    status: "open",
    priority: "low",
    category: "Garage",
    group: "Parents' House",
    createdAt: "3 days ago",
    updatedAt: "3 days ago",
    diagnosis: "Dry rollers and hinges",
    confidence: 95,
    difficulty: "Easy",
    diyCost: 12.98,
    proCost: 95,
    resolvedBy: null,
    assignee: { name: "Robert Q" },
  },
  {
    id: "4",
    title: "Flickering lights in living room",
    icon: IoFlash,
    iconColor: "text-yellow-400",
    iconBg: "bg-yellow-500/20",
    status: "completed",
    priority: "high",
    category: "Electrical",
    group: "My Apartment",
    createdAt: "2 weeks ago",
    updatedAt: "1 week ago",
    resolvedAt: "1 week ago",
    diagnosis: "Loose wire connection at junction box",
    confidence: 78,
    difficulty: "Professional Required",
    diyCost: 0,
    proCost: 125,
    resolvedBy: "pro",
    savedAmount: 0,
    assignee: { name: "Alex Chen" },
    proUsed: "Spark Electric",
  },
  {
    id: "5",
    title: "Water heater maintenance",
    icon: IoWater,
    iconColor: "text-orange-400",
    iconBg: "bg-orange-500/20",
    status: "completed",
    priority: "medium",
    category: "Plumbing",
    group: "My Apartment",
    createdAt: "3 weeks ago",
    updatedAt: "2 weeks ago",
    resolvedAt: "2 weeks ago",
    diagnosis: "Sediment buildup requiring flush",
    confidence: 96,
    difficulty: "Easy",
    diyCost: 0,
    proCost: 225,
    resolvedBy: "diy",
    savedAmount: 225,
    assignee: { name: "Alex Chen" },
  },
  {
    id: "6",
    title: "Clogged bathroom drain",
    icon: IoWater,
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/20",
    status: "completed",
    priority: "medium",
    category: "Plumbing",
    group: "My Apartment",
    createdAt: "1 month ago",
    updatedAt: "1 month ago",
    resolvedAt: "3 weeks ago",
    diagnosis: "Hair and soap buildup in P-trap",
    confidence: 94,
    difficulty: "Easy",
    diyCost: 12,
    proCost: 150,
    resolvedBy: "diy",
    savedAmount: 138,
    assignee: { name: "Jamie Lee" },
  },
  {
    id: "7",
    title: "Broken window lock",
    icon: IoHome,
    iconColor: "text-red-400",
    iconBg: "bg-red-500/20",
    status: "open",
    priority: "high",
    category: "Security",
    group: "Parents' House",
    createdAt: "1 day ago",
    updatedAt: "1 day ago",
    diagnosis: "Latch mechanism worn - replacement needed",
    confidence: 89,
    difficulty: "Easy",
    diyCost: 18,
    proCost: 85,
    resolvedBy: null,
    assignee: { name: "Robert Q" },
  },
  {
    id: "8",
    title: "Dishwasher not draining",
    icon: IoConstruct,
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/20",
    status: "completed",
    priority: "medium",
    category: "Appliances",
    group: "My Apartment",
    createdAt: "2 months ago",
    updatedAt: "6 weeks ago",
    resolvedAt: "6 weeks ago",
    diagnosis: "Clogged filter and drain hose kink",
    confidence: 91,
    difficulty: "Easy",
    diyCost: 0,
    proCost: 175,
    resolvedBy: "diy",
    savedAmount: 175,
    assignee: { name: "Alex Chen" },
  },
];

export const categoryData: ChartDataItem[] = [
  { name: "Plumbing", value: 4, color: "#3ECF8E" },
  { name: "HVAC", value: 1, color: "#3ECF8E" },
  { name: "Electrical", value: 1, color: "#f59e0b" },
  { name: "Appliances", value: 1, color: "#8b5cf6" },
  { name: "Security", value: 1, color: "#ef4444" },
];

export const savingsOverTimeData: SavingsDataItem[] = [
  { month: "Aug", savings: 0, issues: 1 },
  { month: "Sep", savings: 175, issues: 2 },
  { month: "Oct", savings: 313, issues: 1 },
  { month: "Nov", savings: 451, issues: 2 },
  { month: "Dec", savings: 538, issues: 1 },
  { month: "Jan", savings: 538, issues: 1 },
];

export const resolutionData: ChartDataItem[] = [
  { name: "DIY", value: 3, color: "#3ECF8E" },
  { name: "Professional", value: 1, color: "#8b5cf6" },
];
